# Generated by Django 4.2.1 on 2023-05-14 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='資格名')),
                ('detail', models.TextField(blank=True, max_length=500, null=True, verbose_name='資格詳細')),
            ],
        ),
        migrations.CreateModel(
            name='RecordCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='記録項目')),
            ],
        ),
        migrations.CreateModel(
            name='TargetStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='目標ステータス')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('instruction', models.TextField(blank=True, max_length=1000, null=True, verbose_name='自己紹介')),
                ('birth_day', models.DateField(blank=True, null=True, verbose_name='誕生日')),
                ('icon_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='アイコン画像')),
            ],
        ),
        migrations.CreateModel(
            name='TargetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=100, verbose_name='目標')),
                ('target_deadline', models.DateField(blank=True, null=True, verbose_name='目標期限')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.targetstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='勉強内容')),
                ('study_time', models.DurationField(verbose_name='勉強時間')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('follow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_user', to=settings.AUTH_USER_MODEL)),
                ('followed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CertificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(blank=True, null=True, verbose_name='結果')),
                ('exam_date', models.DateField(verbose_name='受験日')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('certiication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.certification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
