# Generated by Django 4.2.1 on 2023-06-20 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_instruction_userprofile_introduction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificationrecord',
            old_name='certiication',
            new_name='certification',
        ),
    ]
