# Generated by Django 4.2.1 on 2023-08-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_certiication_certificationrecord_certification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='icon_img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='アイコン画像'),
        ),
    ]
