# Generated by Django 4.2.1 on 2023-08-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userprofile_icon_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='icon_img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='アイコン画像'),
        ),
    ]
